### understanding car insurance data

In [1]:
import sys
import pandas as pd

from src import load_clean_data, load_raw_data
sys.path.append("../src")
file_path  = '../data/raw/MachineLearningRating_v3.txt'
insurance_df = load_raw_data(file_path)
insurance_df.head()

INFO:src.utils.load_data:Loaded 1000098 records from ../data/raw/MachineLearningRating_v3.txt.

,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,Citizenship,LegalType,Title,Language,Bank,AccountType,...,ExcessSelected,CoverCategory,CoverType,CoverGroup,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims
0,145249,12827,2015-03-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
1,145249,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
2,145249,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0
3,145255,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,512.848070,0.0
4,145255,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0

In [2]:
insurance_df.columns

Index(['UnderwrittenCoverID', 'PolicyID', 'TransactionMonth',
       'IsVATRegistered', 'Citizenship', 'LegalType', 'Title', 'Language',
       'Bank', 'AccountType', 'MaritalStatus', 'Gender', 'Country', 'Province',
       'PostalCode', 'MainCrestaZone', 'SubCrestaZone', 'ItemType', 'mmcode',
       'VehicleType', 'RegistrationYear', 'make', 'Model', 'Cylinders',
       'cubiccapacity', 'kilowatts', 'bodytype', 'NumberOfDoors',
       'VehicleIntroDate', 'CustomValueEstimate', 'AlarmImmobiliser',
       'TrackingDevice', 'CapitalOutstanding', 'NewVehicle', 'WrittenOff',
       'Rebuilt', 'Converted', 'CrossBorder', 'NumberOfVehiclesInFleet',
       'SumInsured', 'TermFrequency', 'CalculatedPremiumPerTerm',
       'ExcessSelected', 'CoverCategory', 'CoverType', 'CoverGroup', 'Section',
       'Product', 'StatutoryClass', 'StatutoryRiskType', 'TotalPremium',
       'TotalClaims'],
      dtype='object')

In [3]:

columns = [
    'UnderwrittenCoverID', 'PolicyID', 'TransactionMonth',
    'IsVATRegistered', 'Citizenship', 'LegalType', 'Title', 'Language',
    'Bank', 'AccountType', 'MaritalStatus', 'Gender', 'Country', 'Province',
    'PostalCode', 'MainCrestaZone', 'SubCrestaZone', 'ItemType', 'mmcode',
    'VehicleType', 'RegistrationYear', 'make', 'Model', 'Cylinders',
    'cubiccapacity', 'kilowatts', 'bodytype', 'NumberOfDoors',
    'VehicleIntroDate', 'CustomValueEstimate', 'AlarmImmobiliser',
    'TrackingDevice', 'CapitalOutstanding', 'NewVehicle', 'WrittenOff',
    'Rebuilt', 'Converted', 'CrossBorder', 'NumberOfVehiclesInFleet',
    'SumInsured', 'TermFrequency', 'CalculatedPremiumPerTerm',
    'ExcessSelected', 'CoverCategory', 'CoverType', 'CoverGroup', 'Section',
    'Product', 'StatutoryClass', 'StatutoryRiskType', 'TotalPremium',
    'TotalClaims'
]

# Categorizing columns
column_groups = {
    "policy_info": [
        'UnderwrittenCoverID', 'PolicyID', 'TransactionMonth',
        'TermFrequency', 'CalculatedPremiumPerTerm', 'ExcessSelected',
        'CoverCategory', 'CoverType', 'CoverGroup', 'Section', 'Product',
        'StatutoryClass', 'StatutoryRiskType'
    ],
    "customer_info": [
        'IsVATRegistered', 'Citizenship', 'LegalType', 'Title', 'Language',
        'Bank', 'AccountType', 'MaritalStatus', 'Gender'
    ],
    "geography": [
        'Country', 'Province', 'PostalCode', 'MainCrestaZone', 'SubCrestaZone'
    ],
    "vehicle_info": [
        'ItemType', 'mmcode', 'VehicleType', 'RegistrationYear', 'make', 'Model',
        'Cylinders', 'cubiccapacity', 'kilowatts', 'bodytype', 'NumberOfDoors',
        'VehicleIntroDate', 'CustomValueEstimate', 'NewVehicle', 'WrittenOff',
        'Rebuilt', 'Converted', 'CrossBorder', 'NumberOfVehiclesInFleet'
    ],
    "vehicle_security": [
        'AlarmImmobiliser', 'TrackingDevice'
    ],
    "financials": [
        'CapitalOutstanding', 'SumInsured', 'TotalPremium', 'TotalClaims'
    ]
}

# Optional: print nicely
for group, cols in column_groups.items():
    print(f"\n{group.upper()} ({len(cols)} columns):")
    print(", ".join(cols))

POLICY_INFO (13 columns):
UnderwrittenCoverID, PolicyID, TransactionMonth, TermFrequency, CalculatedPremiumPerTerm, ExcessSelected, CoverCategory, CoverType, CoverGroup, Section, Product, StatutoryClass, StatutoryRiskType

CUSTOMER_INFO (9 columns):
IsVATRegistered, Citizenship, LegalType, Title, Language, Bank, AccountType, MaritalStatus, Gender

GEOGRAPHY (5 columns):
Country, Province, PostalCode, MainCrestaZone, SubCrestaZone

VEHICLE_INFO (19 columns):
ItemType, mmcode, VehicleType, RegistrationYear, make, Model, Cylinders, cubiccapacity, kilowatts, bodytype, NumberOfDoors, VehicleIntroDate, CustomValueEstimate, NewVehicle, WrittenOff, Rebuilt, Converted, CrossBorder, NumberOfVehiclesInFleet

VEHICLE_SECURITY (2 columns):
AlarmImmobiliser, TrackingDevice

FINANCIALS (4 columns):
CapitalOutstanding, SumInsured, TotalPremium, TotalClaims

In [4]:

insurance_df.isnull().sum()

UnderwrittenCoverID               0
PolicyID                          0
TransactionMonth                  0
IsVATRegistered                   0
Citizenship                       0
LegalType                         0
Title                             0
Language                          0
Bank                         145961
AccountType                   40232
MaritalStatus                  8259
Gender                         9536
Country                           0
Province                          0
PostalCode                        0
MainCrestaZone                    0
SubCrestaZone                     0
ItemType                          0
mmcode                          552
VehicleType                     552
RegistrationYear                  0
make                            552
Model                           552
Cylinders                       552
cubiccapacity                   552
kilowatts                       552
bodytype                        552
NumberOfDoors                   552
VehicleIntroDate                552
CustomValueEstimate          779642
AlarmImmobiliser                  0
TrackingDevice                    0
CapitalOutstanding                2
NewVehicle                   153295
WrittenOff                   641901
Rebuilt                      641901
Converted                    641901
CrossBorder                  999400
NumberOfVehiclesInFleet     1000098
SumInsured                        0
TermFrequency                     0
CalculatedPremiumPerTerm          0
ExcessSelected                    0
CoverCategory                     0
CoverType                         0
CoverGroup                        0
Section                           0
Product                           0
StatutoryClass                    0
StatutoryRiskType                 0
TotalPremium                      0
TotalClaims                       0
dtype: int64

In [6]:
missing_info = insurance_df.isnull().sum().to_frame('MissingCount')
missing_info['Percent'] = 100 * missing_info['MissingCount'] / len(insurance_df)
missing_info = missing_info[missing_info['MissingCount'] > 0]
print(missing_info.sort_values('Percent', ascending=False))

                         MissingCount     Percent
NumberOfVehiclesInFleet       1000098  100.000000
CrossBorder                    999400   99.930207
CustomValueEstimate            779642   77.956560
WrittenOff                     641901   64.183810
Converted                      641901   64.183810
Rebuilt                        641901   64.183810
NewVehicle                     153295   15.327998
Bank                           145961   14.594670
AccountType                     40232    4.022806
Gender                           9536    0.953507
MaritalStatus                    8259    0.825819
mmcode                            552    0.055195
VehicleType                       552    0.055195
make                              552    0.055195
VehicleIntroDate                  552    0.055195
NumberOfDoors                     552    0.055195
bodytype                          552    0.055195
kilowatts                         552    0.055195
cubiccapacity                     552    0.055195
Cylinders                         552    0.055195
Model                             552    0.055195
CapitalOutstanding                  2    0.000200