In [2]:
import sys
import pandas as pd

from src import load_clean_data, load_raw_data,save_processed_data
sys.path.append("../src")
file_path  = '../data/raw/MachineLearningRating_v3.txt'
insurance_df = load_raw_data(file_path)
insurance_df.head()

INFO:src.utils.load_data:Loaded 1000098 records from ../data/raw/MachineLearningRating_v3.txt.

,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,Citizenship,LegalType,Title,Language,Bank,AccountType,...,ExcessSelected,CoverCategory,CoverType,CoverGroup,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims
0,145249,12827,2015-03-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,9.000000e-13
1,145249,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.000000e+00
2,145249,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.000000e+00
3,1452155,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,512.848070,0.000000e+00
4,145255,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.000000e+00

In [3]:
insurance_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000098 entries, 0 to 1000097
Data columns (total 52 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   UnderwrittenCoverID       1000098 non-null  int64
 1   PolicyID                  1000098 non-null  int64
 2   TransactionMonth          1000098 non-null  object
 3   IsVATRegistered           1000098 non-null  bool
 4   Citizenship               1000098 non-null  object
 5   LegalType                 1000098 non-null  object
 6   Title                     1000098 non-null  object
 7   Language                  1000098 non-null  object
 8   Bank                      854137 non-null   object
 9   AccountType               959866 non-null   object
 10  MaritalStatus             991839 non-null   object
 11  Gender                    990562 non-null   object
 12  Country                   1000098 non-null  object
 13  Province                  1000098 non-null  object
 14  PostalCode                1000098 non-null  int64
 15  MainCrestaZone            1000098 non-null  object
 16  SubCrestaZone             1000098 non-null  object
 17  ItemType                  1000098 non-null  object
 18  mmcode                    999546 non-null   float64
 19  VehicleType               999546 non-null   object
 20  RegistrationYear          1000098 non-null  int64
 21  make                      999546 non-null   object
 22  Model                     999546 non-null   object
 23  Cylinders                 999546 non-null   float64
 24  cubiccapacity             999546 non-null   float64
 25  kilowatts                 999546 non-null   float64
 26  bodytype                  999546 non-null   object
 27  NumberOfDoors             999546 non-null   float64
 28  VehicleIntroDate          999546 non-null   object
 29  CustomValueEstimate       220456 non-null   float64
 30  AlarmImmobiliser          1000098 non-null  object
 31  TrackingDevice            1000098 non-null  object
 32  CapitalOutstanding        1000096 non-null  object
 33  NewVehicle                846803 non-null   object
 34  WrittenOff                358197 non-null   object
 35  Rebuilt                   358197 non-null   object
 36  Converted                 358197 non-null   object
 37  CrossBorder               698 non-null      object
 38  NumberOfVehiclesInFleet   0 non-null        float64
 39  SumInsured                1000098 non-null  float64
 40  TermFrequency             1000098 non-null  object
 41  CalculatedPremiumPerTerm  1000098 non-null  float64
 42  ExcessSelected            1000098 non-null  object
 43  CoverCategory             1000098 non-null  object
 44  CoverType                 1000098 non-null  object
 45  CoverGroup                1000098 non-null  object
 46  Section                   1000098 non-null  object
 47  Product                   1000098 non-null  object
 48  StatutoryClass            1000098 non-null  object
 49  StatutoryRiskType         1000098 non-null  object
 50  TotalPremium              1000098 non-null  float64
 51  TotalClaims               1000098 non-null  float64
dtypes: bool(1), float64(11), int64(4), object(36)
memory usage: 390.1+ MB

### describe the data before cleaning

In [4]:
insurance_df.describe()

,UnderwrittenCoverID,PolicyID,PostalCode,mmcode,RegistrationYear,Cylinders,cubiccapacity,kilowatts,NumberOfDoors,CustomValueEstimate,NumberOfVehiclesInFleet,SumInsured,CalculatedPremiumPerTerm,TotalPremium,TotalClaims
count,1.000098e+06,1.000098e+06,1.000098e+06,9.995460e+05,1.000098e+06,999546.000000,999546.000000,999546.000000,999546.000000,2.204560e+05,0.0,1.000098e+06,1.000098e+06,1.000098e+06,1.000098e+06
mean,1.048189e+05,7.956682e+03,3.020601e+03,5.487770e+07,2.010225e+03,4.046642,2466.743258,97.207919,4.019250,2.255311e+05,NaN,6.041727e+05,1.178757e+02,6.190550e+01,6.486119e+01
std,6.330803e+04,5.290039e+03,2.649854e+03,1.360381e+07,3.261391e+00,0.294020,442.800640,19.393256,0.468314,5.645157e+05,NaN,1.508332e+06,3.997017e+02,2.302845e+02,2.384075e+03
min,1.000000e+00,1.400000e+01,1.000000e+00,4.041200e+06,1.987000e+03,0.000000,0.000000,0.000000,0.000000,2.000000e+04,NaN,1.000000e-02,0.000000e+00,-7.825768e+02,-1.200241e+04
25%,5.514300e+04,4.500000e+03,8.270000e+02,6.005692e+07,2.008000e+03,4.000000,2237.000000,75.000000,4.000000,1.350000e+05,NaN,5.000000e+03,3.224800e+00,0.000000e+00,0.000000e+00
50%,9.408300e+04,7.071000e+03,2.000000e+03,6.005842e+07,2.011000e+03,4.000000,2694.000000,111.000000,4.000000,2.200000e+05,NaN,7.500000e+03,8.436900e+00,2.178333e+00,0.000000e+00
75%,1.391900e+05,1.107700e+04,4.180000e+03,6.005842e+07,2.013000e+03,4.000000,2694.000000,111.000000,4.000000,2.800000e+05,NaN,2.500000e+05,9.000000e+01,2.192982e+01,0.000000e+00
max,1.452155e+06,2.324600e+04,9.870000e+03,6.506535e+07,2.015000e+03,10.000000,12880.000000,309.000000,6.000000,2.655000e+07,NaN,1.263620e+07,7.442217e+04,6.528260e+04,3.930921e+05

### NumberOfVehiclesInFleet (1,000,098 missing)

In [5]:
insurance_df = insurance_df.drop('NumberOfVehiclesInFleet', axis=1)

In [6]:
insurance_df = insurance_df.drop('CrossBorder', axis=1)

In [7]:
insurance_df.describe()

,UnderwrittenCoverID,PolicyID,PostalCode,mmcode,RegistrationYear,Cylinders,cubiccapacity,kilowatts,NumberOfDoors,CustomValueEstimate,SumInsured,CalculatedPremiumPerTerm,TotalPremium,TotalClaims
count,1.000098e+06,1.000098e+06,1.000098e+06,9.995460e+05,1.000098e+06,999546.000000,999546.000000,999546.000000,999546.000000,2.204560e+05,1.000098e+06,1.000098e+06,1.000098e+06,1.000098e+06
mean,1.048189e+05,7.956682e+03,3.020601e+03,5.487770e+07,2.010225e+03,4.046642,2466.743258,97.207919,4.019250,2.255311e+05,6.041727e+05,1.178757e+02,6.190550e+01,6.486119e+01
std,6.330803e+04,5.290039e+03,2.649854e+03,1.360381e+07,3.261391e+00,0.294020,442.800640,19.393256,0.468314,5.645157e+05,1.508332e+06,3.997017e+02,2.302845e+02,2.384075e+03
min,1.000000e+00,1.400000e+01,1.000000e+00,4.041200e+06,1.987000e+03,0.000000,0.000000,0.000000,0.000000,2.000000e+04,1.000000e-02,0.000000e+00,-7.825768e+02,-1.200241e+04
25%,5.514300e+04,4.500000e+03,8.270000e+02,6.005692e+07,2.008000e+03,4.000000,2237.000000,75.000000,4.000000,1.350000e+05,5.000000e+03,3.224800e+00,0.000000e+00,0.000000e+00
50%,9.408300e+04,7.071000e+03,2.000000e+03,6.005842e+07,2.011000e+03,4.000000,2694.000000,111.000000,4.000000,2.200000e+05,7.500000e+03,8.436900e+00,2.178333e+00,0.000000e+00
75%,1.391900e+05,1.107700e+04,4.180000e+03,6.005842e+07,2.013000e+03,4.000000,2694.000000,111.000000,4.000000,2.800000e+05,2.500000e+05,9.000000e+01,2.192982e+01,0.000000e+00
max,1.452155e+06,2.324600e+04,9.870000e+03,6.506535e+07,2.015000e+03,10.000000,12880.000000,309.000000,6.000000,2.655000e+07,1.263620e+07,7.442217e+04,6.528260e+04,3.930921e+05

In [8]:
insurance_df['CustomValueEstimate'] = insurance_df.groupby('VehicleType')['CustomValueEstimate'].transform(lambda x: x.fillna(x.median()))

In [9]:
insurance_df.isnull().sum()

UnderwrittenCoverID              0
PolicyID                         0
TransactionMonth                 0
IsVATRegistered                  0
Citizenship                      0
LegalType                        0
Title                            0
Language                         0
Bank                        145961
AccountType                  40232
MaritalStatus                 8259
Gender                        9536
Country                          0
Province                         0
PostalCode                       0
MainCrestaZone                   0
SubCrestaZone                    0
ItemType                         0
mmcode                         552
VehicleType                    552
RegistrationYear                 0
make                           552
Model                          552
Cylinders                      552
cubiccapacity                  552
kilowatts                      552
bodytype                       552
NumberOfDoors                  552
VehicleIntroDate               552
CustomValueEstimate            552
AlarmImmobiliser                 0
TrackingDevice                   0
CapitalOutstanding               2
NewVehicle                  153295
WrittenOff                  641901
Rebuilt                     641901
Converted                   641901
SumInsured                       0
TermFrequency                    0
CalculatedPremiumPerTerm         0
ExcessSelected                   0
CoverCategory                    0
CoverType                        0
CoverGroup                       0
Section                          0
Product                          0
StatutoryClass                   0
StatutoryRiskType                0
TotalPremium                     0
TotalClaims                      0
dtype: int64

In [10]:
missing_vechicle_type = insurance_df[insurance_df['VehicleType'].isnull()]
missing_vechicle_type.head()

,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,Citizenship,LegalType,Title,Language,Bank,AccountType,...,ExcessSelected,CoverCategory,CoverType,CoverGroup,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims
487033,74751,3844,2015-02-01 00:00:00,False,,Individual,Mr,English,Nedbank,Savings account,...,No excess,Keys and Alarms,Keys and Alarms,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,Commercial,IFRS Constant,0.000000,0.0
512140,74753,3844,2014-10-01 00:00:00,False,,Individual,Mr,English,Nedbank,Savings account,...,No excess,Signage and Vehicle Wraps,Signage and Vehicle Wraps,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,Commercial,IFRS Constant,0.521842,0.0
512141,74753,3844,2014-12-01 00:00:00,False,,Individual,Mr,English,Nedbank,Savings account,...,No excess,Signage and Vehicle Wraps,Signage and Vehicle Wraps,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,Commercial,IFRS Constant,0.000000,0.0
512142,74753,3844,2015-03-01 00:00:00,False,,Individual,Mr,English,Nedbank,Savings account,...,No excess,Signage and Vehicle Wraps,Signage and Vehicle Wraps,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,Commercial,IFRS Constant,0.000000,0.0
512143,74753,3844,2015-05-01 00:00:00,False,,Individual,Mr,English,Nedbank,Savings account,...,No excess,Signage and Vehicle Wraps,Signage and Vehicle Wraps,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,Commercial,IFRS Constant,0.000000,0.0

In [11]:
print(missing_vechicle_type[['make', 'Model', 'Province', 'TotalClaims']].head())

       make Model    Province  TotalClaims
487033  NaN   NaN  Mpumalanga          0.0
512140  NaN   NaN  Mpumalanga          0.0
512141  NaN   NaN  Mpumalanga          0.0
512142  NaN   NaN  Mpumalanga          0.0
512143  NaN   NaN  Mpumalanga          0.0

###  Calculate the mode of VehicleType

In [12]:

vehicle_type_mode = insurance_df['VehicleType'].mode()[0]
vehicle_type_mode

'Passenger Vehicle'

### Impute missing values with the mode

In [13]:
insurance_df['VehicleType'] = insurance_df['VehicleType'].fillna(vehicle_type_mode)

In [14]:
insurance_df.isnull().sum()

UnderwrittenCoverID              0
PolicyID                         0
TransactionMonth                 0
IsVATRegistered                  0
Citizenship                      0
LegalType                        0
Title                            0
Language                         0
Bank                        145961
AccountType                  40232
MaritalStatus                 8259
Gender                        9536
Country                          0
Province                         0
PostalCode                       0
MainCrestaZone                   0
SubCrestaZone                    0
ItemType                         0
mmcode                         552
VehicleType                      0
RegistrationYear                 0
make                           552
Model                          552
Cylinders                      552
cubiccapacity                  552
kilowatts                      552
bodytype                       552
NumberOfDoors                  552
VehicleIntroDate               552
CustomValueEstimate            552
AlarmImmobiliser                 0
TrackingDevice                   0
CapitalOutstanding               2
NewVehicle                  153295
WrittenOff                  641901
Rebuilt                     641901
Converted                   641901
SumInsured                       0
TermFrequency                    0
CalculatedPremiumPerTerm         0
ExcessSelected                   0
CoverCategory                    0
CoverType                        0
CoverGroup                       0
Section                          0
Product                          0
StatutoryClass                   0
StatutoryRiskType                0
TotalPremium                     0
TotalClaims                      0
dtype: int64

### CustomValueEstimate (779,642 missing):
Explanation: This column represents the estimated value of the vehicle, which is crucial for calculating premiums and assessing risk. However, ~78% missing values indicate inconsistent data collection.
Implication: Missing values here could skew your analysis of profitability (e.g., Loss Ratio) or modeling of premiums. You can:
Impute missing values (e.g., using median or mean by VehicleType or make).
Exclude rows with missing CustomValueEstimate for specific analyses.
Use it cautiously in modeling, as imputation may introduce bias.

In [15]:
insurance_df['CustomValueEstimate'] = insurance_df.groupby('VehicleType')['CustomValueEstimate'].transform(lambda x: x.fillna(x.median()))

In [16]:
insurance_df.isnull().sum()

UnderwrittenCoverID              0
PolicyID                         0
TransactionMonth                 0
IsVATRegistered                  0
Citizenship                      0
LegalType                        0
Title                            0
Language                         0
Bank                        145961
AccountType                  40232
MaritalStatus                 8259
Gender                        9536
Country                          0
Province                         0
PostalCode                       0
MainCrestaZone                   0
SubCrestaZone                    0
ItemType                         0
mmcode                         552
VehicleType                      0
RegistrationYear                 0
make                           552
Model                          552
Cylinders                      552
cubiccapacity                  552
kilowatts                      552
bodytype                       552
NumberOfDoors                  552
VehicleIntroDate               552
CustomValueEstimate              0
AlarmImmobiliser                 0
TrackingDevice                   0
CapitalOutstanding               2
NewVehicle                  153295
WrittenOff                  641901
Rebuilt                     641901
Converted                   641901
SumInsured                       0
TermFrequency                    0
CalculatedPremiumPerTerm         0
ExcessSelected                   0
CoverCategory                    0
CoverType                        0
CoverGroup                       0
Section                          0
Product                          0
StatutoryClass                   0
StatutoryRiskType                0
TotalPremium                     0
TotalClaims                      0
dtype: int64

In [17]:
# Impute categorical columns
for col in ['Gender', 'MaritalStatus', 'Bank', 'AccountType', 'WrittenOff', 'Rebuilt', 'Converted']:
    insurance_df[col] = insurance_df[col].fillna(insurance_df[col].mode()[0])
for col in ['mmcode', 'VehicleType', 'make', 'Model', 'bodytype', 'VehicleIntroDate']:
    insurance_df[col] = insurance_df[col].fillna(insurance_df[col].mode()[0])
# Impute numerical columns
for col in ['Cylinders', 'cubiccapacity', 'kilowatts', 'NumberOfDoors', 'CapitalOutstanding']:
    insurance_df[col] = pd.to_numeric(insurance_df[col], errors='coerce')
    insurance_df[col] = insurance_df[col].fillna(int(insurance_df[col].median()))
    insurance_df['NewVehicle'] = insurance_df['NewVehicle'].fillna(
    insurance_df['RegistrationYear'].apply(lambda x: 'Yes' if x >= 2023 else 'No'))

In [18]:
insurance_df.isnull().sum()

UnderwrittenCoverID         0
PolicyID                    0
TransactionMonth            0
IsVATRegistered             0
Citizenship                 0
LegalType                   0
Title                       0
Language                    0
Bank                        0
AccountType                 0
MaritalStatus               0
Gender                      0
Country                     0
Province                    0
PostalCode                  0
MainCrestaZone              0
SubCrestaZone               0
ItemType                    0
mmcode                      0
VehicleType                 0
RegistrationYear            0
make                        0
Model                       0
Cylinders                   0
cubiccapacity               0
kilowatts                   0
bodytype                    0
NumberOfDoors               0
VehicleIntroDate            0
CustomValueEstimate         0
AlarmImmobiliser            0
TrackingDevice              0
CapitalOutstanding          0
NewVehicle                  0
WrittenOff                  0
Rebuilt                     0
Converted                   0
SumInsured                  0
TermFrequency               0
CalculatedPremiumPerTerm    0
ExcessSelected              0
CoverCategory               0
CoverType                   0
CoverGroup                  0
Section                     0
Product                     0
StatutoryClass              0
StatutoryRiskType           0
TotalPremium                0
TotalClaims                 0
dtype: int64

In [19]:


data = save_processed_data(insurance_df)

INFO:src.utils.save_data:Successfully saved 1000098 records to /Users/worash/Desktop/tenx/week3/car-insurance-predictive-model/data/clean/car_insurance_processed.txt

In [20]:
data.head()

,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,Citizenship,LegalType,Title,Language,Bank,AccountType,...,ExcessSelected,CoverCategory,CoverType,CoverGroup,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims
0,145249,12827,2015-03-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,9.000000e-13
1,145249,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.000000e+00
2,145249,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.000000e+00
3,1452155,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,512.848070,0.000000e+00
4,145255,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.000000e+00